import data from './app.json';
import Icon from './library/cell/icon/icon';
import IconBar from './library/cell/icon/tissue/bar/icon-bar';
import IconLinkBar from './library/cell/icon/tissue/bar/icon-link-bar';

export default function Index() {
    return (
        <div>
            <h1>Next.js</h1>
            <p>Generated by Next.js</p>
            <Icon icon ={data.icon}/>
            <IconBar iconBar = {data.iconBar} />
            <IconLinkBar iconLinkBar = {data.iconLinkBar} />
        </div>
    )
}