import data from './app.json';
import AlloyFooter from './library/tissue/footer/footer';
import AlloyNavBar from './library/tissue/nav/navbar';

export default function Index() {
    return (
        <div>
            <AlloyNavBar navBar = {data.navBar} />
            <h1>Next.js</h1>
            <p>Generated by Next.js</p>
            <AlloyFooter footer = {data.footer} />
        </div>
    )
}