"use client"; // This is a client component 
import data from './app.json';
import AlloyButton from './library/cell/button/button';
import AlloyButtonIcon from './library/cell/button/button-icon';
import AlloyCard from './library/cell/card/card';
import AlloyFooter from './library/tissue/footer/footer';
import AlloyNavBar from './library/tissue/nav/navbar';

import { useState } from 'react';

export default function Index() {
    const [buttonOutput, setButtonOutput] = useState('');

    const handleButtonClick = (output) => {
        setButtonOutput(output);
    };

    return (
        <div>
            <AlloyNavBar navBar={data.navBar} />
            <h1>Next.js</h1>
            <p>Generated by Next.js</p>
            <AlloyButton button={data.button} onClick={handleButtonClick} />
            <AlloyButtonIcon buttonIcon={data.buttonIcon} onClick={handleButtonClick} />
            <p>{buttonOutput}</p>
            <AlloyCard card={data.card} />
            <AlloyFooter footer={data.footer} />
        </div>
    );
}